# Be sure to restart your server when you modify this file.

# Add new inflection rules using the following format. Inflections
# are locale specific, and you may define rules for as many different
# locales as you wish. All of these examples are active by default:
# ActiveSupport::Inflector.inflections(:en) do |inflect|
#   inflect.plural /^(ox)$/i, '\1en'
#   inflect.singular /^(ox)en/i, '\1'
#   inflect.irregular 'person', 'people'
#   inflect.uncountable %w( fish sheep )
# end

# These inflection rules are supported but not enabled by default:
# ActiveSupport::Inflector.inflections(:en) do |inflect|
#   inflect.acronym 'RESTful'
# end

ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym 'CEO'
  inflect.acronym 'CFO'
  inflect.acronym 'CTO'
  inflect.acronym 'GE'
  inflect.acronym 'NPR'
  inflect.acronym 'TV'
  inflect.acronym 'FBI'
  inflect.acronym 'AI'
  inflect.acronym 'MIT'
  inflect.acronym 'GOP'
  inflect.acronym 'USA'
  inflect.acronym 'IBM'
  inflect.acronym 'FDA'
  inflect.acronym 'API'
  inflect.acronym 'DHH'
  inflect.acronym 'WWDC'
  inflect.acronym 'VP'
  inflect.acronym 'SVP'
  inflect.acronym 'UK'
  inflect.acronym 'EU'
  inflect.acronym 'ECB'
  inflect.acronym 'IoT'
  inflect.acronym 'GPU'
  inflect.acronym 'VC'
  inflect.acronym 'PR'
  inflect.acronym 'iPhone' # Only partially works. Titleize will return "IPhone". But it's better than "I Phone"
  inflect.acronym 'iPad'
  inflect.acronym 'iTunes'
  inflect.acronym 'iPod'
  inflect.acronym 'USB'
  inflect.acronym 'CNN'
  inflect.acronym 'NBC'
  inflect.acronym 'HP'
  inflect.acronym 'GM'
  inflect.acronym 'BBC'
  inflect.acronym 'LP'
  inflect.acronym 'DSSTNE'
  inflect.acronym 'IPO'
  inflect.acronym 'ESPN'
  inflect.acronym 'IMF'
  inflect.acronym 'GDPR'
  inflect.acronym 'iOS'
  inflect.acronym 'NASA'
  inflect.acronym 'USA'
  inflect.acronym 'NHL'
  inflect.acronym 'NFL'
  inflect.acronym 'MLB'
  inflect.acronym 'NBA'
  inflect.acronym 'CBC'
  inflect.acronym 'AL'
  inflect.acronym 'AK'
  inflect.acronym 'AZ'
  inflect.acronym 'AR'
  inflect.acronym 'CA'
  inflect.acronym 'CO'
  inflect.acronym 'CT'
  inflect.acronym 'DE'
  inflect.acronym 'FL'
  inflect.acronym 'GA'
  inflect.acronym 'HI'
  inflect.acronym 'ID'
  inflect.acronym 'IL'
  inflect.acronym 'IN'
  inflect.acronym 'IA'
  inflect.acronym 'KS'
  inflect.acronym 'KY'
  inflect.acronym 'LA'
  inflect.acronym 'ME'
  inflect.acronym 'MD'
  inflect.acronym 'MA'
  inflect.acronym 'MI'
  inflect.acronym 'MN'
  inflect.acronym 'MS'
  inflect.acronym 'MO'
  inflect.acronym 'MT'
  inflect.acronym 'NE'
  inflect.acronym 'NH'
  inflect.acronym 'NJ'
  inflect.acronym 'NM'
  inflect.acronym 'NY'
  inflect.acronym 'NC'
  inflect.acronym 'ND'
  inflect.acronym 'OH'
  inflect.acronym 'OK'
  inflect.acronym 'OR'
  inflect.acronym 'PA'
  inflect.acronym 'RI'
  inflect.acronym 'SC'
  inflect.acronym 'SD'
  inflect.acronym 'TN'
  inflect.acronym 'TX'
  inflect.acronym 'UT'
  inflect.acronym 'VT'
  inflect.acronym 'VA'
  inflect.acronym 'WA'
  inflect.acronym 'WV'
  inflect.acronym 'WI'
  inflect.acronym 'WY'
  inflect.acronym 'AB'
  inflect.acronym 'BC'
  inflect.acronym 'MB'
  inflect.acronym 'NB'
  inflect.acronym 'NL'
  inflect.acronym 'NT'
  inflect.acronym 'NS'
  inflect.acronym 'NU'
  inflect.acronym 'ON'
  inflect.acronym 'PE'
  inflect.acronym 'QC'
  inflect.acronym 'SK'
  inflect.acronym 'YT'
end
